version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: emailing-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: emailing-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BenTech$#5428
      MYSQL_DATABASE: emaildb
      MYSQL_USER: BenTech
      MYSQL_PASSWORD: BenTech$#5428
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: emailing-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: BenTech
      PMA_PASSWORD: BenTech$#5428
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
